  name: Deploy main website on push

on:
  push:
    branches: [ "main" ]
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get latest code
        uses: actions/checkout@v3

      - name: Use Node.js 17.x
        uses: actions/setup-node@v3
        with:
          node-version: '17'

      - name: Build Project
        run: |
          npm install
          npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: h26.seohost.pl
          username: github-actions@e-sasiad.pl
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: false
          local-dir: dist/
          server-dir: public_html